CREATE TABLE IF NOT EXISTS `wdsavs_ai_session` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `session_id` VARCHAR(64) NOT NULL,
  `session_type` VARCHAR(32) NOT NULL,
  `initiator_type` VARCHAR(32) NOT NULL,
  `initiator_id` VARCHAR(128) DEFAULT NULL,
  `source_node_id` VARCHAR(128) DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL,
  `context_summary` TEXT DEFAULT NULL,
  `title` VARCHAR(128) DEFAULT NULL,
  `collaboration_mode` VARCHAR(32) DEFAULT NULL,
  `coordinator_node_id` VARCHAR(128) DEFAULT NULL,
  `coordinator_epoch` BIGINT DEFAULT NULL,
  `collaboration_policy_json` TEXT DEFAULT NULL,
  `expire_at` VARCHAR(32) DEFAULT NULL,
  `create_time` VARCHAR(32) NOT NULL,
  `update_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_session_session_id` (`session_id`),
  KEY `idx_ai_session_source_node_id` (`source_node_id`),
  KEY `idx_ai_session_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_session_participant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `session_id` VARCHAR(64) NOT NULL,
  `node_id` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `join_time` VARCHAR(32) NOT NULL,
  `update_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_session_participant` (`session_id`, `node_id`),
  KEY `idx_ai_session_participant_session` (`session_id`),
  KEY `idx_ai_session_participant_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_model_config` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `provider_code` VARCHAR(64) NOT NULL,
  `display_name` VARCHAR(128) NOT NULL,
  `protocol` VARCHAR(32) NOT NULL,
  `base_url` VARCHAR(512) NOT NULL,
  `api_path` VARCHAR(256) DEFAULT NULL,
  `api_key` VARCHAR(1024) DEFAULT NULL,
  `model_name` VARCHAR(128) NOT NULL,
  `temperature` DOUBLE DEFAULT NULL,
  `top_p` DOUBLE DEFAULT NULL,
  `max_tokens` INT DEFAULT NULL,
  `presence_penalty` DOUBLE DEFAULT NULL,
  `frequency_penalty` DOUBLE DEFAULT NULL,
  `extra_body_json` MEDIUMTEXT DEFAULT NULL,
  `extra_headers_json` MEDIUMTEXT DEFAULT NULL,
  `enabled` TINYINT(1) NOT NULL DEFAULT 1,
  `default_config` TINYINT(1) NOT NULL DEFAULT 0,
  `create_user` VARCHAR(64) DEFAULT NULL,
  `create_time` VARCHAR(32) DEFAULT NULL,
  `modify_user` VARCHAR(64) DEFAULT NULL,
  `modify_time` VARCHAR(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_model_provider_code` (`provider_code`),
  KEY `idx_ai_model_enabled` (`enabled`),
  KEY `idx_ai_model_default` (`default_config`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_task` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `task_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `parent_task_id` VARCHAR(64) DEFAULT NULL,
  `request_id` VARCHAR(128) DEFAULT NULL,
  `task_type` VARCHAR(64) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `current_stage` VARCHAR(64) DEFAULT NULL,
  `source_node_id` VARCHAR(128) DEFAULT NULL,
  `target_node_id` VARCHAR(128) DEFAULT NULL,
  `request_payload_json` MEDIUMTEXT DEFAULT NULL,
  `result_json` MEDIUMTEXT DEFAULT NULL,
  `error_code` VARCHAR(64) DEFAULT NULL,
  `error_message` TEXT DEFAULT NULL,
  `timeout_ms` BIGINT DEFAULT NULL,
  `retry_count` INT NOT NULL DEFAULT 0,
  `max_retries` INT NOT NULL DEFAULT 0,
  `start_time` VARCHAR(32) DEFAULT NULL,
  `end_time` VARCHAR(32) DEFAULT NULL,
  `create_time` VARCHAR(32) NOT NULL,
  `update_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_task_task_id` (`task_id`),
  KEY `idx_ai_task_session_id` (`session_id`),
  KEY `idx_ai_task_parent_task_id` (`parent_task_id`),
  KEY `idx_ai_task_request_id` (`request_id`),
  KEY `idx_ai_task_status` (`status`),
  KEY `idx_ai_task_source_target` (`source_node_id`, `target_node_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_agent_run` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `agent_run_id` VARCHAR(64) NOT NULL,
  `task_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `node_id` VARCHAR(128) DEFAULT NULL,
  `agent_role` VARCHAR(64) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `input_summary` TEXT DEFAULT NULL,
  `output_summary` TEXT DEFAULT NULL,
  `start_time` VARCHAR(32) DEFAULT NULL,
  `end_time` VARCHAR(32) DEFAULT NULL,
  `create_time` VARCHAR(32) NOT NULL,
  `update_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_agent_run_id` (`agent_run_id`),
  KEY `idx_ai_agent_run_task_id` (`task_id`),
  KEY `idx_ai_agent_run_session_id` (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_relay_node` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `node_id` VARCHAR(128) NOT NULL,
  `host` VARCHAR(255) NOT NULL,
  `port` INT NOT NULL,
  `relay_endpoint` VARCHAR(512) NOT NULL,
  `version` VARCHAR(64) DEFAULT NULL,
  `protocol_version` VARCHAR(32) DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL,
  `capabilities_json` MEDIUMTEXT DEFAULT NULL,
  `workspace_root` VARCHAR(1024) DEFAULT NULL,
  `last_heartbeat_time` VARCHAR(32) DEFAULT NULL,
  `register_time` VARCHAR(32) NOT NULL,
  `create_time` VARCHAR(32) NOT NULL,
  `update_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_relay_node_node_id` (`node_id`),
  KEY `idx_ai_relay_node_status` (`status`),
  KEY `idx_ai_relay_node_host_port` (`host`, `port`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_relay_heartbeat` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `node_id` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `active_sessions` INT DEFAULT NULL,
  `cpu_load` DECIMAL(8,4) DEFAULT NULL,
  `memory_usage` BIGINT DEFAULT NULL,
  `last_task_time` VARCHAR(32) DEFAULT NULL,
  `detail_json` MEDIUMTEXT DEFAULT NULL,
  `heartbeat_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_ai_relay_heartbeat_node_id` (`node_id`),
  KEY `idx_ai_relay_heartbeat_time` (`heartbeat_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_relay_grant` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `grant_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `request_id` VARCHAR(64) NOT NULL,
  `source_node_id` VARCHAR(128) NOT NULL,
  `target_node_id` VARCHAR(128) NOT NULL,
  `allowed_capabilities_json` MEDIUMTEXT DEFAULT NULL,
  `signed_token` MEDIUMTEXT DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL,
  `expire_at` VARCHAR(32) NOT NULL,
  `revoked_at` VARCHAR(32) DEFAULT NULL,
  `reason` TEXT DEFAULT NULL,
  `create_time` VARCHAR(32) NOT NULL,
  `update_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_relay_grant_grant_id` (`grant_id`),
  UNIQUE KEY `uk_ai_relay_grant_request_id` (`request_id`),
  KEY `idx_ai_relay_grant_session_id` (`session_id`),
  KEY `idx_ai_relay_grant_source_target` (`source_node_id`, `target_node_id`),
  KEY `idx_ai_relay_grant_expire_at` (`expire_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_deploy_record` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `deploy_id` VARCHAR(64) NOT NULL,
  `task_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `target_node_id` VARCHAR(128) NOT NULL,
  `deploy_mode` VARCHAR(32) NOT NULL,
  `artifact_version` VARCHAR(64) DEFAULT NULL,
  `script_path` VARCHAR(1024) DEFAULT NULL,
  `artifact_path` VARCHAR(1024) DEFAULT NULL,
  `status` VARCHAR(32) NOT NULL,
  `stderr_summary` TEXT DEFAULT NULL,
  `stdout_summary` TEXT DEFAULT NULL,
  `exit_code` INT DEFAULT NULL,
  `retryable` TINYINT(1) NOT NULL DEFAULT 0,
  `start_time` VARCHAR(32) DEFAULT NULL,
  `end_time` VARCHAR(32) DEFAULT NULL,
  `create_time` VARCHAR(32) NOT NULL,
  `update_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_deploy_record_deploy_id` (`deploy_id`),
  KEY `idx_ai_deploy_record_task_id` (`task_id`),
  KEY `idx_ai_deploy_record_target_node_id` (`target_node_id`),
  KEY `idx_ai_deploy_record_deploy_mode` (`deploy_mode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_task_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(64) NOT NULL,
  `task_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `payload_json` MEDIUMTEXT DEFAULT NULL,
  `sequence_no` BIGINT NOT NULL,
  `created_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_task_event_event_id` (`event_id`),
  KEY `idx_ai_task_event_task_sequence` (`task_id`, `sequence_no`),
  KEY `idx_ai_task_event_session_id` (`session_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_session_context_event` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `event_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `task_id` VARCHAR(64) DEFAULT NULL,
  `sender_type` VARCHAR(32) DEFAULT NULL,
  `sender_id` VARCHAR(128) DEFAULT NULL,
  `target_node_id` VARCHAR(128) DEFAULT NULL,
  `role` VARCHAR(32) NOT NULL,
  `content` TEXT DEFAULT NULL,
  `content_type` VARCHAR(32) NOT NULL,
  `content_ref` VARCHAR(1024) DEFAULT NULL,
  `created_time` VARCHAR(32) NOT NULL,
  `checksum` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_session_context_event_id` (`event_id`),
  KEY `idx_ai_session_context_session_cursor` (`session_id`, `id`),
  KEY `idx_ai_session_context_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_session_message_queue` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `queue_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) NOT NULL,
  `source_node_id` VARCHAR(128) DEFAULT NULL,
  `target_node_id` VARCHAR(128) NOT NULL,
  `request_id` VARCHAR(128) NOT NULL,
  `status` VARCHAR(32) NOT NULL,
  `request_payload_json` MEDIUMTEXT NOT NULL,
  `response_payload_json` MEDIUMTEXT DEFAULT NULL,
  `error_message` TEXT DEFAULT NULL,
  `attempt_count` INT NOT NULL DEFAULT 0,
  `max_attempts` INT NOT NULL DEFAULT 6,
  `next_attempt_time` BIGINT DEFAULT NULL,
  `lease_until` BIGINT DEFAULT NULL,
  `deferred` TINYINT(1) NOT NULL DEFAULT 0,
  `wake_required` TINYINT(1) NOT NULL DEFAULT 0,
  `wake_dispatched` TINYINT(1) NOT NULL DEFAULT 0,
  `create_time` VARCHAR(32) NOT NULL,
  `update_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_session_message_queue_id` (`queue_id`),
  UNIQUE KEY `uk_ai_session_message_request` (`session_id`, `target_node_id`, `request_id`),
  KEY `idx_ai_session_message_queue_key` (`session_id`, `target_node_id`, `status`),
  KEY `idx_ai_session_message_due` (`status`, `next_attempt_time`),
  KEY `idx_ai_session_message_wake` (`wake_required`, `wake_dispatched`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `wdsavs_ai_audit_log` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `audit_id` VARCHAR(64) NOT NULL,
  `session_id` VARCHAR(64) DEFAULT NULL,
  `task_id` VARCHAR(64) DEFAULT NULL,
  `source_node_id` VARCHAR(128) DEFAULT NULL,
  `target_node_id` VARCHAR(128) DEFAULT NULL,
  `event_type` VARCHAR(64) NOT NULL,
  `decision` VARCHAR(32) DEFAULT NULL,
  `detail_json` MEDIUMTEXT DEFAULT NULL,
  `operator_type` VARCHAR(32) DEFAULT NULL,
  `operator_id` VARCHAR(128) DEFAULT NULL,
  `created_time` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_audit_log_audit_id` (`audit_id`),
  KEY `idx_ai_audit_log_session_id` (`session_id`),
  KEY `idx_ai_audit_log_task_id` (`task_id`),
  KEY `idx_ai_audit_log_event_type` (`event_type`),
  KEY `idx_ai_audit_log_created_time` (`created_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



